// identity-provider-mobile-react/src/pages/MapPage.tsx
import React, { useState, useEffect } from 'react';
import {
    IonContent,
    IonHeader,
    IonPage,
    IonTitle,
    IonToolbar,
    IonFab,
    IonFabButton,
    IonIcon,
    IonModal,
    IonButton,
    IonItem,
    IonLabel,
    IonTextarea,
    IonSegment,
    IonSegmentButton,
    IonCard,
    IonCardHeader,
    IonCardTitle,
    IonCardContent,
    IonBadge,
    IonLoading
} from '@ionic/react';
import { add, location, list, logOut } from 'ionicons/icons';
import { MapContainer, TileLayer, Marker, Popup, useMapEvents } from 'react-leaflet';
import { Geolocation } from '@capacitor/geolocation';
import L from 'leaflet';
import axios from 'axios';
import { useHistory } from 'react-router-dom';
import './MapPage.css';
import 'leaflet/dist/leaflet.css';

const API_BASE_URL = 'http://localhost:8080/api';

// Fix marker icons
delete (L.Icon.Default.prototype as any)._getIconUrl;
L.Icon.Default.mergeOptions({
    iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
    iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
    shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

const getMarkerIcon = (status: string) => {
    const colors: any = {
        NOUVEAU: '#ef4444',
        EN_COURS: '#f59e0b',
        TERMINE: '#10b981'
    };

    return L.divIcon({
        className: 'custom-marker',
        html: `<div style="background-color: ${colors[status]}; width: 25px; height: 25px; border-radius: 50%; border: 3px solid white; box-shadow: 0 2px 5px rgba(0,0,0,0.3);"></div>`,
        iconSize: [25, 25],
        iconAnchor: [12, 12]
    });
};

interface RoadIssue {
    id: number;
    latitude: number;
    longitude: number;
    description: string;
    status: string;
    surfaceM2?: number;
    budget?: number;
    companyName?: string;
    createdAt: string;
    reporterId?: number;
}

const MapPage: React.FC = () => {
    const history = useHistory();
    const user = JSON.parse(localStorage.getItem('user') || '{}');
    const [issues, setIssues] = useState<RoadIssue[]>([]);
    const [stats, setStats] = useState<any>(null);
    const [showModal, setShowModal] = useState(false);
    const [newIssueLocation, setNewIssueLocation] = useState<[number, number] | null>(null);
    const [description, setDescription] = useState('');
    const [currentLocation, setCurrentLocation] = useState<[number, number]>([-18.8792, 47.5079]);
    const [filter, setFilter] = useState<'all' | 'mine'>('all');
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        getCurrentLocation();
        loadIssues();
        loadStats();
    }, [filter]);

    const getCurrentLocation = async () => {
        try {
            const position = await Geolocation.getCurrentPosition();
            setCurrentLocation([position.coords.latitude, position.coords.longitude]);
        } catch (error) {
            console.error('Error getting location:', error);
        }
    };

    const loadIssues = async () => {
        try {
            const token = localStorage.getItem('token');
            let url = `${API_BASE_URL}/road-issues`;

            if (filter === 'mine') {
                url += `?reporterId=${user.id}`;
            }

            const response = await axios.get(url, {
                headers: { Authorization: `Bearer ${token}` }
            });
            setIssues(response.data);
        } catch (error) {
            console.error('Error loading issues:', error);
        }
    };

    const loadStats = async () => {
        try {
            const token = localStorage.getItem('token');
            const response = await axios.get(`${API_BASE_URL}/road-issues/stats`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            setStats(response.data);
        } catch (error) {
            console.error('Error loading stats:', error);
        }
    };

    const handleMapClick = (latlng: [number, number]) => {
        setNewIssueLocation(latlng);
        setShowModal(true);
    };

    const handleSubmitIssue = async () => {
        if (!newIssueLocation || !description) {
            alert('Veuillez remplir tous les champs');
            return;
        }

        setLoading(true);
        try {
            const token = localStorage.getItem('token');
            await axios.post(
                `${API_BASE_URL}/road-issues?reporterId=${user.id}`,
                {
                    latitude: newIssueLocation[0],
                    longitude: newIssueLocation[1],
                    description,
                    status: 'NOUVEAU'
                },
                {
                    headers: { Authorization: `Bearer ${token}` }
                }
            );

            setShowModal(false);
            setDescription('');
            setNewIssueLocation(null);
            loadIssues();
            loadStats();
            alert('Signalement créé avec succès');
        } catch (error) {
            console.error('Error creating issue:', error);
            alert('Erreur lors de la création du signalement');
        } finally {
            setLoading(false);
        }
    };

    const handleLogout = () => {
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        history.push('/login');
    };

    const MapClickHandler = () => {
        useMapEvents({
            click: (e) => {
                handleMapClick([e.latlng.lat, e.latlng.lng]);
            }
        });
        return null;
    };

    const getStatusLabel = (status: string) => {
        const labels: any = {
            NOUVEAU: 'Nouveau',
            EN_COURS: 'En cours',
            TERMINE: 'Terminé'
        };
        return labels[status] || status;
    };

    const getStatusColor = (status: string) => {
        const colors: any = {
            NOUVEAU: 'danger',
            EN_COURS: 'warning',
            TERMINE: 'success'
        };
        return colors[status] || 'medium';
    };

    return (
        <IonPage>
            <IonHeader>
                <IonToolbar color="primary">
                    <IonTitle>Carte des Travaux</IonTitle>
                    <IonButton slot="end" fill="clear" onClick={handleLogout}>
                        <IonIcon icon={logOut} />
                    </IonButton>
                </IonToolbar>
            </IonHeader>
            <IonContent>
                {/* Stats */}
                {stats && (
                    <div className="stats-container">
                        <IonCard>
                            <IonCardContent>
                                <div className="stats-grid">
                                    <div className="stat-item">
                                        <div className="stat-value">{stats.totalIssues}</div>
                                        <div className="stat-label">Signalements</div>
                                    </div>
                                    <div className="stat-item">
                                        <div className="stat-value">{stats.totalSurfaceM2?.toFixed(0) || 0}</div>
                                        <div className="stat-label">Surface (m²)</div>
                                    </div>
                                    <div className="stat-item">
                                        <div className="stat-value">{stats.completionPercentage?.toFixed(0) || 0}%</div>
                                        <div className="stat-label">Avancement</div>
                                    </div>
                                </div>
                            </IonCardContent>
                        </IonCard>
                    </div>
                )}

                {/* Filter */}
                <div className="filter-container">
                    <IonSegment value={filter} onIonChange={(e) => setFilter(e.detail.value as any)}>
                        <IonSegmentButton value="all">
                            <IonLabel>Tous</IonLabel>
                        </IonSegmentButton>
                        <IonSegmentButton value="mine">
                            <IonLabel>Mes signalements</IonLabel>
                        </IonSegmentButton>
                    </IonSegment>
                </div>

                {/* Map */}
                <div className="map-container">
                    <MapContainer
                        center={currentLocation}
                        zoom={13}
                        style={{ height: '100%', width: '100%' }}
                    >
                        <TileLayer
                            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                            attribution='&copy; OpenStreetMap contributors'
                        />
                        <MapClickHandler />

                        {/* Current location marker */}
                        <Marker position={currentLocation}>
                            <Popup>Votre position</Popup>
                        </Marker>

                        {/* Issue markers */}
                        {issues.map((issue) => (
                            <Marker
                                key={issue.id}
                                position={[issue.latitude, issue.longitude]}
                                icon={getMarkerIcon(issue.status)}
                            >
                                <Popup>
                                    <div className="popup-content">
                                        <h3>Signalement #{issue.id}</h3>
                                        <IonBadge color={getStatusColor(issue.status)}>
                                            {getStatusLabel(issue.status)}
                                        </IonBadge>
                                        <p>{issue.description}</p>
                                        <p className="popup-date">
                                            {new Date(issue.createdAt).toLocaleDateString()}
                                        </p>
                                    </div>
                                </Popup>
                            </Marker>
                        ))}
                    </MapContainer>
                </div>

                {/* FAB for adding new issue */}
                <IonFab vertical="bottom" horizontal="end" slot="fixed">
                    <IonFabButton onClick={getCurrentLocation}>
                        <IonIcon icon={location} />
                    </IonFabButton>
                </IonFab>

                {/* Modal for new issue */}
                <IonModal isOpen={showModal} onDidDismiss={() => setShowModal(false)}>
                    <IonHeader>
                        <IonToolbar color="primary">
                            <IonTitle>Nouveau Signalement</IonTitle>
                        </IonToolbar>
                    </IonHeader>
                    <IonContent className="ion-padding">
                        <IonItem>
                            <IonLabel position="stacked">Description</IonLabel>
                            <IonTextarea
                                value={description}
                                onIonChange={(e) => setDescription(e.detail.value!)}
                                placeholder="Décrivez le problème routier..."
                                rows={5}
                            />
                        </IonItem>

                        {newIssueLocation && (
                            <IonItem>
                                <IonLabel>
                                    <p>Latitude: {newIssueLocation[0].toFixed(6)}</p>
                                    <p>Longitude: {newIssueLocation[1].toFixed(6)}</p>
                                </IonLabel>
                            </IonItem>
                        )}

                        <IonButton expand="block" onClick={handleSubmitIssue} className="submit-button">
                            Créer le signalement
                        </IonButton>

                        <IonButton expand="block" fill="clear" onClick={() => setShowModal(false)}>
                            Annuler
                        </IonButton>

                        <IonLoading isOpen={loading} message="Création en cours..." />
                    </IonContent>
                </IonModal>
            </IonContent>
        </IonPage>
    );
};

export default MapPage;

// identity-provider-mobile-vue/src/views/MapPage.vue
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar color="primary">
        <ion-title>Carte - Travaux Routiers</ion-title>
        <ion-button slot="end" fill="clear" @click="handleLogout">
          <ion-icon :icon="logOutOutline"></ion-icon>
        </ion-button>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <div class="mobile-map-container">
        <!-- Controls -->
        <div class="map-controls ion-padding">
          <ion-segment v-model="viewMode">
            <ion-segment-button value="all">
              <ion-label>Tous</ion-label>
            </ion-segment-button>
            <ion-segment-button value="mine">
              <ion-label>Mes signalements</ion-label>
            </ion-segment-button>
            <ion-segment-button v-if="currentUser?.role === 'MANAGER'" value="manager">
              <ion-label>Manager</ion-label>
            </ion-segment-button>
          </ion-segment>

          <div v-if="viewMode === 'all'" class="ion-margin-top">
            <ion-item>
              <ion-select v-model="filter" label="Filtrer par statut" label-placement="floating">
                <ion-select-option value="all">Tous</ion-select-option>
                <ion-select-option value="NEW">Nouveaux</ion-select-option>
                <ion-select-option value="IN_PROGRESS">En cours</ion-select-option>
                <ion-select-option value="COMPLETED">Terminés</ion-select-option>
              </ion-select>
            </ion-item>
          </div>

          <div v-if="viewMode === 'mine'" class="ion-margin-top">
             <ion-button expand="block" color="success" @click="goToReport">
               ➕ Signaler un problème
             </ion-button>
          </div>

          <div v-if="viewMode === 'manager'" class="ion-margin-top">
             <ion-list>
               <ion-list-header>
                 <ion-label>Utilisateurs Bloqués</ion-label>
               </ion-list-header>
               <ion-item v-if="blockedUsers.length === 0">
                 <ion-label>Aucun utilisateur bloqué</ion-label>
               </ion-item>
               <ion-item v-for="user in blockedUsers" :key="user.id">
                 <ion-label>
                   <h2>{{ user.firstName }} {{ user.lastName }}</h2>
                   <p>{{ user.email }}</p>
                 </ion-label>
                 <ion-button slot="end" color="success" @click="handleUnblock(user.id)">
                   Débloquer
                 </ion-button>
               </ion-item>
             </ion-list>
          </div>
        </div>

        <!-- Map -->
        <div v-show="viewMode !== 'manager'" id="map" style="height: 60vh; width: 100%;"></div>

        <!-- List (Mobile view) -->
        <div v-show="viewMode !== 'manager'" class="issues-list-mobile ion-padding">
          <h3>{{ viewMode === 'mine' ? 'Mes signalements' : 'Signalements' }} ({{ issues.length }})</h3>
          <ion-list>
            <ion-item v-for="issue in issues" :key="issue.id" lines="none" class="issue-item">
              <ion-label>
                <h2>{{ issue.description }}</h2> <!-- Backend uses description as title usually -->
                <p>
                  <ion-badge :color="getStatusColor(issue.status)">{{ issue.status }}</ion-badge>
                </p>
                <p v-if="issue.surfaceM2">Surface: {{ issue.surfaceM2 }} m²</p>
              </ion-label>
            </ion-item>
          </ion-list>
        </div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { 
  IonPage, IonHeader, IonToolbar, IonTitle, IonContent, 
  IonSegment, IonSegmentButton, IonLabel, 
  IonButton, IonIcon, IonItem, IonSelect, IonSelectOption,
  IonList, IonBadge, IonListHeader, toastController
} from '@ionic/vue';
import { logOutOutline } from 'ionicons/icons';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import roadIssueService from '@/services/roadIssueService';
import authService from '@/services/authService';

const router = useRouter();
const currentUser = authService.getCurrentUser();
const issues = ref<any[]>([]);
const blockedUsers = ref<any[]>([]);
const viewMode = ref('all');
const filter = ref('all');
let map: L.Map | null = null;
let markers: L.LayerGroup | null = null;

// Fix Leaflet icons
delete (L.Icon.Default.prototype as any)._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

const getMarkerIcon = (status: string) => {
    const colors: any = {
        'NEW': '#ef4444', // Red
        'IN_PROGRESS': '#f59e0b', // Orange
        'COMPLETED': '#10b981' // Green
    };
    const color = colors[status] || '#3b82f6';
    
    return L.divIcon({
        className: 'custom-marker',
        html: `<div style="background-color: ${color}; width: 15px; height: 15px; border-radius: 50%; border: 2px solid white; box-shadow: 0 2px 4px rgba(0,0,0,0.3);"></div>`,
        iconSize: [15, 15],
        iconAnchor: [7, 7]
    });
};

const loadBlockedUsers = async () => {
  if (currentUser?.role === 'MANAGER') {
    try {
      blockedUsers.value = await authService.getBlockedUsers();
    } catch (e) {
      console.error(e);
    }
  }
};

const handleUnblock = async (userId: number) => {
  try {
    await authService.unblockUser(userId);
    const toast = await toastController.create({
      message: 'Utilisateur débloqué',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    loadBlockedUsers();
  } catch (e) {
    console.error(e);
  }
};

const loadIssues = async () => {
  try {
    let data;

    if (viewMode.value === 'mine' && currentUser?.id) {
       data = await roadIssueService.getIssuesByReporter(currentUser.id);
    } else if (filter.value !== 'all') {
       data = await roadIssueService.getIssuesByStatus(filter.value);
    } else {
       data = await roadIssueService.getAllIssues();
    }
    issues.value = data;
    updateMarkers();
  } catch (e) {
    console.error(e);
  }
};

const updateMarkers = () => {
  if (!map) return;
  if (markers) map.removeLayer(markers);

  markers = L.layerGroup().addTo(map);

  issues.value.forEach(issue => {
    if (issue.latitude && issue.longitude) {
      L.marker([issue.latitude, issue.longitude], {
        icon: getMarkerIcon(issue.status)
      })
      .bindPopup(`
        <b>${issue.status}</b><br>
        ${issue.description}
      `)
      .addTo(markers!);
    }
  });
};

const handleLogout = () => {
  authService.logout();
  router.replace('/login');
};

const goToReport = () => {
    router.push('/report-issue');
};

const getStatusColor = (status: string) => {
    switch(status) {
      case 'NEW': return 'danger';
      case 'IN_PROGRESS': return 'warning';
      case 'COMPLETED': return 'success';
      default: return 'medium';
    }
};

onMounted(() => {
  map = L.map('map').setView([-18.8792, 47.5079], 13);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; OpenStreetMap'
  }).addTo(map);
  
  loadIssues();
});

watch([viewMode, filter], () => {
  loadIssues();
});
</script>

<style scoped>
.map-controls {
  background: white;
  border-bottom: 1px solid #ddd;
}
.issue-item {
  border-bottom: 1px solid #eee;
  --padding-start: 0;
}
</style>
